version: "3.9"
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api/src:/app:ro
  proxy:
    image: nginx:1.21
    ports:
      - 8000:80
    volumes:
      - bundled:/var/www/static:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
    command: [nginx-debug, "-g", "daemon off;"]
  spa:
    build:
      context: ./spa
    volumes:
      - ./spa/src:/spa/src:ro
      - bundled:/spa/dist
    command: watch --mode development
volumes:
  bundled:
