.PHONY: create

create:
	mkdir -p dist
	python ./sample_json.py ./dist/person_100.json 100
	python ./sample_json.py ./dist/person_1000.json 1000
	python ./sample_json.py ./dist/person_10000.json 10000
	python ./sample_json.py ./dist/person_100000.json 100000
