[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["kamiazya <yuki@kamiazya.tech>"]

[tool.poetry.dependencies]
python = "^3.9"
Faker = "^8.12.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
